# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
      - main
pr: none
name: $(date:yyyyMMdd)$(rev:.r)

pool:
  name: 'ConfigCat Agents'

steps:
  - task: Docker@2
    displayName: build
    inputs:
      containerRegistry: Docker Hub
      repository: "configcat/monday-app"
      command: build
      buildContext: "$(System.DefaultWorkingDirectory)"

  - task: Docker@2
    displayName: push
    inputs:
      containerRegistry: Docker Hub
      command: push
      repository: "configcat/monday-app"
      buildContext: "$(System.DefaultWorkingDirectory)"

  - script: |
      mkdir -pv $(build.artifactstagingdirectory)/output
      rm -rf $(build.artifactstagingdirectory)/output/*
      IMAGEID=$(docker images configcat/monday-app:$(Build.BuildId) --format "{{.ID}}")
      CONTAINERID=$(docker create $IMAGEID)
      docker cp $CONTAINERID:/usr/share/nginx/html/. $(build.artifactstagingdirectory)/output/
      docker rm $CONTAINERID
    displayName: "Copy files from docker image"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(build.artifactstagingdirectory)/output/
      artifact: MondayApp
